name: Run tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run tests
      run: python -m unittest